# Generated by Django 4.1 on 2022-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_alter_product_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_items_json', models.CharField(max_length=5000)),
                ('buyer_phone', models.IntegerField(default=0)),
                ('buyer_email', models.CharField(max_length=115)),
                ('buyer_adress', models.CharField(max_length=115)),
                ('buyer_state', models.CharField(max_length=115)),
                ('buyer_city', models.CharField(max_length=115)),
                ('buyer_zipCode', models.CharField(max_length=10)),
            ],
        ),
    ]
