# Generated by Django 4.1 on 2022-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_items_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
